export const SHAPE_TYPES = {
         HorizontalSeparator: 'HorizontalSeparator',
         VerticalSeparator: 'VerticalSeparator',
         RightArrow: 'RightArrow',
         LeftRightArrow: 'LeftRightArrow',
         StraightLine: 'StraightLine',
         VerticalLine: 'VerticalLine',
         HorizontalLine: 'HorizontalLine',
         Connector: 'Connector',
         ArrowConnector: 'ArrowConnector',
         Ellipse: 'Ellipse',
         Triangle: 'Triangle',
         FunctionalDomain: 'FunctionalDomain',
         Pentagon: 'Pentagon',
         TrialReport: 'TrialReport',
         ITDepartment: 'ITDepartment',
         ProcessMapEnd: 'ProcessMapEnd',
         PentagonPhaseSeparator: 'PentagonPhaseSeparator',
         Hexagon: 'Hexagon',
         SwimLane: 'SwimLane',
         CooperatingGroup: 'CooperatingGroup',
         FreeText: 'FreeText',
         Version: 'Version',
         PublicRole: 'PublicRole',
         DateTime: 'DateTime',
         Comment: 'Comment',
         PhaseSeparator: 'PhaseSeparator',
         Image: 'Image',
         Logo: 'Logo',
         ManualInput: 'ManualInput',
         Rule: 'Rule',
         Activity: 'Activity',
         Role: 'Role',
         Customer: 'Customer',
         BackIn: 'BackIn',
         BackOut: 'BackOut',
         ProcessMapBackIn: 'ProcessMapBackIn',
         ProcessMapBackOut: 'ProcessMapBackOut',
         ERP: 'ERP',
         Decision: 'Decision',
         Event: 'Event',
         ProcessInterface: 'ProcessInterface',
         HexagonInterface: 'HexagonInterface',
         ActivityInterface: 'ActivityInterface',
         SubProcess: 'SubProcess',
         ActivitySubProcess: 'ActivitySubProcess',
         Document: 'Document',
         DataStore: 'DataStore',
         RiskPoint: 'RiskPoint',
         KeyPoint: 'KeyPoint',
         From: 'From',
         To: 'To',
         End: 'End',
         ProblemArea: 'ProblemArea',
         KeySuccessFactor: 'KeySuccessFactor',
         KeyControlPoint: 'KeyControlPoint',
         KeyCompliancePoint: 'KeyCompliancePoint',
         XOR: 'XOR',
         OR: 'OR',
         AND: 'AND',
         ProcessStart: 'ProcessStart',
         ProcessTermination: 'ProcessTermination',
         VirtualRole: 'VirtualRole',
         ITDecision: 'ITDecision',
         IsoscelesTrapezium: 'IsoscelesTrapezium',
         Position: 'Position',
         Organization: 'Organization',
         ProcessLevel1: 'ProcessLevel1',
         ProcessLevel2: 'ProcessLevel2',
         ProcessLevel3: 'ProcessLevel3',
         ProcessLevel4: 'ProcessLevel4',
         DiagramName: 'DiagramName',
         Diamond: 'Diamond',
         Term: 'Term',
       };

export const DIRECTION = {
    LEFT:'LEFT',
    BOTTOM:'BOTTOM',
    TOP_RIGHT:'TOP_RIGHT',
    TOP_LEFT:'TOP_LEFT',
    RIGHT:'RIGHT',
    TOP:'TOP',
    BOTTOM_RIGHT:'BOTTOM_RIGHT',
    BOTTOM_LEFT:'BOTTOM_LEFT'
};